AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  GeradorDicas:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_Gerador_Dicas.main
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 540
      Role: 'arn:aws:iam::223720829886:role/service-role/GeradorDicasFuncao'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(7 minutes)
